mode: statefulset

config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null

  exporters:
    otlp:
      endpoint:
      tls:
        insecure: true

    otlphttp:
      endpoint:
      headers:
        "X-Scope-OrgID":

    prometheusremotewrite:
      endpoint:
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
          - otlp
      metrics:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
          - prometheusremotewrite
      logs:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
#          - debug
          - otlphttp
image:
  repository: "otel/opentelemetry-collector-contrib"

resources:
  requests:
    cpu: "0.1"
    memory: 50Mi
  limits:
    cpu: "0.1"
    memory: 50Mi
